/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_sowmya_callme_DTW_ndk */

#ifndef _Included_com_example_sowmya_callme_DTW_ndk
#define _Included_com_example_sowmya_callme_DTW_ndk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_sowmya_callme_DTW_ndk
 * Method:    findScore
 * Signature: (Ljava/lang/String;Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_sowmya_callme_DTW_1ndk_findScore
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
